apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devopslab-prod

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5

images:
  - name: devopslab-backend
    newTag: latest
  - name: devopslab-frontend
    newTag: latest
