# Default values for devopslab
# This is a YAML-formatted file.

# Global configuration
global:
  environment: production
  imageRegistry: ""
  imagePullSecrets: []

# Database configuration
database:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  config:
    database: devopslab
    user: postgres
  secret:
    password: password

# Backend configuration
backend:
  enabled: true
  image:
    repository: devopslab-backend
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  config:
    nodeEnv: production
    port: 3001
  service:
    type: ClusterIP
    port: 80
    targetPort: 3001

# Frontend configuration
frontend:
  enabled: true
  image:
    repository: devopslab-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 3
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
  config:
    apiUrl: "http://backend-service:80"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: devopslab.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod security context
podSecurityContext: {}

# Container security context
securityContext: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
